// @vitest-environment jsdom

import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { init, Terminal } from "ghostty-web";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import {
  captureTerminalContextMenuState,
  forwardTerminalData,
  writeTerminalOutput,
} from "./ThreadTerminalView";

const canvasContext = new Proxy(
  {},
  {
    get: (_target, name) =>
      name === "measureText"
        ? (text: string) => ({
            width: text.length * 9,
            actualBoundingBoxAscent: 12,
            actualBoundingBoxDescent: 4,
          })
        : () => undefined,
    set: () => true,
  },
);

function openTerminal(host: HTMLElement): Terminal {
  vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(
    canvasContext as CanvasRenderingContext2D,
  );
  const terminal = new Terminal({ cols: 80, rows: 24 });
  terminal.open(host);
  return terminal;
}

function nextFrame(): Promise<void> {
  return new Promise((resolve) => requestAnimationFrame(() => resolve()));
}

beforeAll(async () => {
  await init();
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("ghostty terminal", () => {
  it("does not send terminal protocol replies generated by replayed output", async () => {
    render(<div data-testid="terminal-host" />);
    const terminal = openTerminal(screen.getByTestId("terminal-host"));
    const onInput = vi.fn<(dataBase64: string) => void>();
    const onUserInput = vi.fn();
    const replayWriteState = { suppressedWriteCount: 0 };
    terminal.onData((data) => {
      forwardTerminalData({
        data,
        onInput,
        onUserInput,
        replayWriteState,
        sessionStatus: "running",
      });
    });

    writeTerminalOutput({
      data: "\u001b[6n",
      isReplay: true,
      replayWriteState,
      terminal,
    });
    await nextFrame();

    expect(onInput).not.toHaveBeenCalled();
    expect(onUserInput).not.toHaveBeenCalled();

    writeTerminalOutput({
      data: "\u001b[6n",
      isReplay: false,
      replayWriteState,
      terminal,
    });
    await nextFrame();

    expect(onInput).toHaveBeenCalledOnce();
    const encodedReply = onInput.mock.calls[0]?.[0];
    if (encodedReply === undefined) {
      throw new Error("Expected a cursor-position reply");
    }
    expect(Buffer.from(encodedReply, "base64").toString("utf8")).toBe(
      "\u001b[1;1R",
    );
    expect(onUserInput).toHaveBeenCalledOnce();
    expect(replayWriteState.suppressedWriteCount).toBe(0);
    terminal.dispose();
  });

  it("captures the selection when the context menu opens", async () => {
    let capturedSelection = "";
    render(
      <div
        onContextMenuCapture={() => {
          capturedSelection = captureTerminalContextMenuState({
            link: null,
            terminal,
          }).selectionText;
        }}
      >
        <div data-testid="terminal-host" />
      </div>,
    );
    const terminal = openTerminal(screen.getByTestId("terminal-host"));
    await new Promise<void>((resolve) => {
      terminal.write("alpha bravo charlie", resolve);
    });
    terminal.select(0, 0, 5);

    const canvas = screen
      .getByTestId("terminal-host")
      .querySelector<HTMLCanvasElement>("canvas");
    if (canvas === null) {
      throw new Error("Expected the terminal canvas");
    }
    fireEvent.contextMenu(canvas, { button: 2, clientX: 18, clientY: 27 });

    expect(capturedSelection).toBe("alpha");
    terminal.dispose();
  });
});
